{
    'name': 'monBridge Payment',
    'version': '19.0.1.0.0',
    'summary': 'International payment management for monBridge',
    'category': 'Accounting/Accounting',
    'author': 'monBridge',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/company_views.xml',
        'views/beneficiary_views.xml',
        'views/deposit_views.xml',
        'views/fx_quote_views.xml',
        'views/payment_views.xml',
        'views/transaction_views.xml',
        'views/ai_extraction_views.xml',
        'views/menus.xml',
    ],
    'application': True,
    'installable': True,
}
